settings:
  lang:   en    # controls all template section headings (see src/translate.yaml) and loads the respective CV data file
  accent: rgb("#775582")
  text:   rgb("#1c1c1c")
  meta:   rgb("#666666")
  font:   "Libertinus Serif"
  size:   10pt

toc:
  - ["Cover Letter", 2]
  - ["Curriculum Vitae", 3]
  - ["Certificates & Testimonials", 5]

certificates:
  - High School Diploma
  - University Certificates
  - Driver's Licenses
  - Personal ID
